[package]
name = "nellymoser-rs"
version = "0.1.2"
authors = ["relrelb <relrelbachar@gmail.com>"]
edition = "2021"
description = "A pure Rust decoder for the Nellymoser audio codec"
license = "MIT"

[dependencies]
bitstream-io = "1.3.0"
once_cell = "1.10.0"
rustdct = "0.7.0"
